# Generated by Django 3.1.5 on 2021-01-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.TextField(max_length=200, verbose_name='Informacion del producto'),
        ),
    ]
